language: ruby
env:
  - DB=postgres
rvm:
  - 2.0.0
bundler_args: --without development
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup
  - npm install